### ISSUE TITLE
Download files but content is the html mediafire page

### ISSUE THREAD

**Issue by cisKeh** [NicKoehler/mediafire_bulk_downloader#11]
It seems it create all files from the selected directory but fill them with html code instead of what it really is. 

```
304K    One Piece --Edicion Original- Eiichiro Oda- - Tomo 001.cbr

> less *001.cbr

<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title>One Piece ([Edicion Original] Eiichiro Oda) - Tomo 001</title>
<meta name="keywords" content="online storage, free storage, cloud Storage, collaboration, backup file Sharing, share Files, photo backup, photo sharing, ftp replacement, cross platform, remote access, mobile access, send large files, recover files, file versioning, undelete, Windows, PC, Mac, OS X, Linux, iPhone, iPad, Android" />
<meta name="description" content="MediaFire is a simple to use free service that lets you put all your photos, documents, music, and video in a single place so you can access them anywhere and share them everywhere." />
.......
```

Url:
https://www.mediafire.com/folder/9lqr9supanbno/00+inc+-+One+Piece+(Eiichiro+Oda)#r6sqg6c8odkk0

**Comment by NicKoehler** [comment]
can you try updating to my last commit?

**Comment by cisKeh** [comment]
Thks for your quick answer !

I did try again with your update. But sadly, it now seems there is a SSLError

```
Exception in thread Thread-5 (download_file):
Traceback (most recent call last):
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\urllib3\response.py", line 737, in _error_catcher
    yield
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\urllib3\response.py", line 862, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\urllib3\response.py", line 845, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ciskeh\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\ciskeh\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ciskeh\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1253, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ciskeh\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2559)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\urllib3\response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\urllib3\response.py", line 935, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\urllib3\response.py", line 861, in _raw_read
    with self._error_catcher():
  File "C:\Users\ciskeh\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    raise SSLError(e) from e
urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2559)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ciskeh\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\ciskeh\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\mediafire.py", line 440, in download_file
    for chunk in r.iter_content(chunk_size=4096):
  File "C:\Users\ciskeh\Downloads\mediafire_bulk_downloader-master(1)\mediafire_bulk_downloader-master\venv\Lib\site-packages\requests\models.py", line 824, in generate
    raise RequestsSSLError(e)
requests.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2559)
```

**Comment by NicKoehler** [comment]
Googling the error leads to some things you can try to do.

Try this:

`pip install urllib3 --upgrade`
