### ISSUE TITLE
Error when trying to download

### ISSUE THREAD

**Issue by hamdache203** [NicKoehler/mediafire_bulk_downloader#12]
Here's the error:

Downloading Dungeon Crawler Carl 05 The Butchers Masquerade.m4a
Traceback (most recent call last): 
  File "/mediafire_bulk_downloader/mediafire.py", line 468, in <module>
    main()
  File "/mediafire_bulk_downloader/mediafire.py", line 171, in main
    get_file(key, args.output)
  File "/mediafire_bulk_downloader/mediafire.py", line 366, in get_file
    download_file(file_data)
  File "/mediafire_bulk_downloader/mediafire.py", line 438, in download_file
    r.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.mediafire.com/file/j47w9wsiqp3ddr9/Dungeon_Crawler_Carl_05_The_Butchers_Masquerade.m4a/file

**Comment by NicKoehler** [comment]
Can you access this URL in your browser? It appears to be a network issue. I downloaded this file without any errors.
