### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by symmetricalbyte** [NicKoehler/mediafire_bulk_downloader#17]
**Describe the bug**
Not downloading any folder/file

```Downloading super secret file
Exception in thread Thread-1 (download_file):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mediafire.py", line 461, in download_file
    download_link = soup.find("a", {"id": "downloadButton"}).attrs["href"]
AttributeError: 'NoneType' object has no attribute 'attrs'
All downloads completed```

**Comment by NicKoehler** [comment]
Can you post the download link?
